# Copy to the default config location and edit to your liking

[database]
file = "~/.local/share/notelog.db"

[colors]
enabled = true

# ANSI colors for the CLI, use 0 or unset to disable
default = 0
timestamp = 0
ago = 0
tag = 0
note = 0
deleted = 2
edits = 2

[note]
# May have a note
may = [
    "water", "pee", "poop", "masturbate",
    "shower", "teeth", "nails", "shave",
    "sleep", "nap", "wake"
]

# Must have a note
must = [
    "begin", "fail", "complete",
    "note", "dream", "health",
    "food", "coffee"
]

# Must have one of these notes
[note.limit]
coffee = ["begin", "complete"]